### ISSUE TITLE
服务器崩溃

### ISSUE THREAD

**Issue by BrokenDawn627** [the-doo/x-enchant#10]
哥 局域网联机现在是没问题了 但是服务器出bug了
启动不了

**Comment by the-doo** [comment]
完了呀，我试了下服务器启动，一堆错。。。我的锅。。。
我从来没玩过服务器模式，都是单人单机，所以其他模式的问题比较多
不好意思哈，我先改一改

**Comment by the-doo** [comment]
大兄弟，我这边已经改完了，你要不试一下，我不太清楚正常服务器是怎么启动的

这个是链接
https://github.com/the-doo/x-enchant/releases/download/1.18-4.2/x-enchant-1.18-4.2.jar

**Comment by BrokenDawn627** [comment]
我试试

**Comment by BrokenDawn627** [comment]
服务器正常启动了 我进服务器看看功能正不正常

**Comment by the-doo** [comment]
我试了试 自动钓鱼无法触发

**Comment by BrokenDawn627** [comment]
附魔书拿得出来 但是在铁砧里附不上去

**Comment by BrokenDawn627** [comment]
弓箭的附魔书

**Comment by BrokenDawn627** [comment]
会突然闪一下然后消失

**Comment by the-doo** [comment]
创造模式吗

**Comment by BrokenDawn627** [comment]
是的 所有附魔都是

**Comment by BrokenDawn627** [comment]
生存模式也附不上去

**Comment by the-doo** [comment]
ok 你再重新下载试试  同样的版本号 我这边用了另一种修复方式

**Comment by the-doo** [comment]
我本地开单机及modpack都是正常的了 我现在试试局域网的 能不能用

**Comment by BrokenDawn627** [comment]
恩 再发一下文件

**Comment by BrokenDawn627** [comment]
额不好意思我的

**Comment by BrokenDawn627** [comment]
客户端忘记换模组了

**Comment by BrokenDawn627** [comment]
额 换了还是附不上去

**Comment by BrokenDawn627** [comment]
使用指令附魔的话会显示是未知的魔咒

**Comment by the-doo** [comment]
你这边的最新更新计划是什么时间节点呢

**Comment by BrokenDawn627** [comment]
其实不急的 我可以把内容攒多一点再更

**Comment by BrokenDawn627** [comment]
等下 可以了

**Comment by BrokenDawn627** [comment]
重下了一下能用了

**Comment by the-doo** [comment]
我刚刚发现了个小bug 假如钓鱼使用了 更多战利品及图书管理员 直接可以走向人生巅峰

**Comment by BrokenDawn627** [comment]
没事我可以暂时先ban掉 要不你先发新版本

**Comment by BrokenDawn627** [comment]
后面再慢慢改

**Comment by BrokenDawn627** [comment]
好像也不是很巅峰啊hh 可能是我脸黑吧

**Comment by the-doo** [comment]
我小小的改了下, 掉落, 应该没那么夸张了

新版本已经发了, 正在等待审核
