### ISSUE TITLE
护甲附魔刷在怪物身上导致崩溃

### ISSUE THREAD

**Issue by BrokenDawn627** [the-doo/x-enchant#11]
因为我这里装了一个improvedmobs的模组 然后可能是怪物身上刷出了带有x-enchant附魔的护甲 然后玩家打了一下就崩了

**Comment by BrokenDawn627** [comment]
[crash-2022-02-12_19.14.06-server.txt](https://github.com/the-doo/x-enchant/files/8053264/crash-2022-02-12_19.14.06-server.txt)

**Comment by BrokenDawn627** [comment]
在服务器崩的

**Comment by the-doo** [comment]
禁用消息提示即可

**Comment by the-doo** [comment]
我这边改一下

**Comment by BrokenDawn627** [comment]
恩 修好了的话我这边发个热修复版本 毕竟会崩服 挺严重的

**Comment by BrokenDawn627** [comment]
是把chatTips关了就行是吧

**Comment by the-doo** [comment]
不好意思哈 还是由于昨天的问题 就是聊天ui是客户端才有的 服务器没有

所以当玩家杀了怪触发 更多战利品的时候 会在聊天框发一句话 导致服务器崩了

**Comment by BrokenDawn627** [comment]
所以禁用了之后就没事了是吧

**Comment by BrokenDawn627** [comment]
确实有更多战利品附魔 我再去问问改了之后会不会崩

**Comment by the-doo** [comment]
我直接使用了客户端的发送聊天导致的崩溃, 不应该这么做， 现在是在找怎么从服务器发送聊天信息

**Comment by BrokenDawn627** [comment]
禁用了之后确实不会崩了

**Comment by the-doo** [comment]
嘿嘿 ok了 正在审核中😀😀😀
