### ISSUE TITLE
禁用魔免附魔不生效且魔免附魔存在问题

### ISSUE THREAD

**Issue by BrokenDawn627** [the-doo/x-enchant#12]
哥 我又来了QAQ 这次是听群友反馈说魔免附魔会把一些饰品带的力量效果一起去除掉 然后我就禁用了 但是禁用了之后在rei仍然能查到

**Comment by BrokenDawn627** [comment]
还有可以稍微调高一下光环药水效果的时间 不然夜视光环会一直闪

**Comment by the-doo** [comment]
我这看下代码检查下魔免是啥问题,
药水效果下个版本调高到10s

我的锅，这个是QQ ~ 917728956
