### ISSUE TITLE
药水效果光环白/黑名单功能添加请求

### ISSUE THREAD

**Issue by BrokenDawn627** [the-doo/x-enchant#2]
如题，有些别的模组的药水效果也会成为光环附魔，我想禁用其中一些不好的效果，希望您可以添加此功能，谢谢。

**Comment by the-doo** [comment]
新版本已经添加了！！！

**Comment by BrokenDawn627** [comment]
感谢 但是新版本有个问题 就是在modmenu自带的设置选项里面设置的话会直接崩游戏 手动到config里面设置还没试过
