### ISSUE TITLE
部分物品不能正常堆叠

### ISSUE THREAD

**Issue by unninie** [the-doo/x-enchant#29]
比如合成出来的火把和敲下来的火把，宝箱里的苹果和树叶掉落的，有时候下矿一些石头和矿也不能正常堆叠但不知道怎么触发的。目前解决方法是把不能堆叠的物品丢出去再捡回来

**Comment by pat277** [comment]
This error also happens with me. I believe the error occurs depending on how the item is gotten, either from mining it, or finding it in a randomly generated chest

**Comment by the-doo** [comment]
收到 目前 在尝试重现库😂

**Comment by the-doo** [comment]
Ok了, 原因是工具提示时, 我直接使用了错误的方法导致的, 现在已经正常了
