### ISSUE TITLE
光环药水效果1级对应效果两级

### ISSUE THREAD

**Issue by BrokenDawn627** [the-doo/x-enchant#6]
又发现一个问题  抱歉 又打扰了 
就是一级的光环 穿在身上是两级 MC里面0级药水效果才是1级

**Comment by BrokenDawn627** [comment]
哥 要不你给我个便捷点的联系方式吧

**Comment by the-doo** [comment]
😂之前是 一级对应一级  
有一个版本改了 想着是好光环比较难获取 所以就改成附魔等级+1了 
如果觉得1:1比较合理 我下个版本再改回来 同时再加点其他附魔

**Comment by BrokenDawn627** [comment]
主要是附魔名字上面是I 实际上是II 对不上就感觉很奇怪

**Comment by BrokenDawn627** [comment]
可以说是强迫症犯了 而且这样一来就没有1级药水效果对应的附魔了

**Comment by BrokenDawn627** [comment]
我是觉得光环上面的药水等级已经超过原版不作弊下能获得的最高等级了 没必要再高了

**Comment by the-doo** [comment]
ok 下个版本会调整回来 同时会添加些新的附魔😀

**Comment by BrokenDawn627** [comment]
哥再和你提个建议 最好能再加个功能就是可以调节光环附魔的等级上限 现在最高是5级 对应效果6级 但是抗性提升6=减伤120%=无敌了 我搞了把99999攻击力的剑都砍不动

**Comment by the-doo** [comment]
😂好的, 我现在添加上这个配置

**Comment by the-doo** [comment]
> 😂好的, 我现在添加上这个配置

不过，只能添加个全局的，比较快

**Comment by the-doo** [comment]
可以了 大兄弟 
最新1.18-4版本尽情享用~~~
最近比较忙 所以可能响应慢了点 抱歉哈😊
