### ISSUE TITLE
局域网联机问题

### ISSUE THREAD

**Issue by BrokenDawn627** [the-doo/x-enchant#8]
哥我把部分药水效果禁用以后 局域网联机就出问题了 两个人的客户端确认是完全一样的

**Comment by BrokenDawn627** [comment]
![QQ图片20220209193223](https://user-images.githubusercontent.com/50197440/153192065-eb9c41c9-571d-42f7-b571-58b2e99ca384.png)

**Comment by BrokenDawn627** [comment]
[latest.log](https://github.com/the-doo/x-enchant/files/8032256/latest.log)

**Comment by the-doo** [comment]
。。。这么严重吗。。。方便知道操作路径吗。。。我这边复现一下

**Comment by the-doo** [comment]
操作路径就是说，出现这个结果之前做了什么操作及步骤
我这边尝试复现一下，局域网模式及禁用部分药水效果是吗，尽量争取快些解决  
不好意思 耽误您发版了
😂😂😂
还有 无限整合包 我就是玩这个测试的。。。不过只是单人模式。。。

**Comment by BrokenDawn627** [comment]
额就是正常的房主打开转发到局域网 其他人加入时就会报错

**Comment by the-doo** [comment]
新版本已经发布，待审核中，非常感谢大佬的Issues，辛苦了辛苦了

**Comment by BrokenDawn627** [comment]
麻烦您了 这几天每天都来找您修bug 打扰了 新版本我之后找个时间再测试下
